version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: keystone
      POSTGRES_PASSWORD: keystone
      POSTGRES_DB: keystone_vendor_dashboard
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
